### ISSUE TITLE
Team Consistency

### ISSUE THREAD

**Issue by sz16900** [Flakster/Smashing-Magazine-heatmap#1]
Great Job on the website guys, it looks better than the original!!

There are a few things we should start paying attention to:

- I've noticed that in several places you guys switch your units from %, to px, to em's ... It would be a better idea if before you guys sit down to code, to have a general consensus on which types of units you guys are going to be working with. That way your code looks consistent and a future developer can understand your code.

- When you are working with CSS Grid, if you find yourselves writing "grid-template-column: 1fr 1fr 1fr 1fr 1fr 1fr" .... its probably a better idea to start using a function such as repeat(5, 1fr) etc... keeps it cleaner.

**Comment by sz16900** [comment]
- Same thing with colour... at some places you guys use rgb, then hex and then named colors... keep it consistent

**Comment by Flakster** [comment]
OK, you are totally right!
